In [1]:
%matplotlib inline
import numpy as np
import torch
torch.set_printoptions(edgeitems=2, linewidth=75)

In [2]:
t_c = torch.tensor([0.5, 14.0, 15.0, 28.0, 11.0,
                    8.0, 3.0, -4.0, 6.0, 13.0, 21.0])
t_u = torch.tensor([35.7, 55.9, 58.2, 81.9, 56.3, 48.9,
                    33.9, 21.8, 48.4, 60.4, 68.4])
t_un = 0.1 * t_u

In [20]:
def model(t_u, w2, w1, b):
    return w2 * t_u**2 + w1 * t_u + b

In [36]:
params = torch.tensor([4.0, 1.0, 0.0], requires_grad=True)
learning_rate = 1e-4
optimizer = optim.SGD([params], lr=learning_rate) # <1>

training_loop(
    n_epochs = 5000, 
    optimizer = optimizer,
    params = params, # <1> 
    t_u = t_un,
    t_c = t_c)

Epoch 5, Loss 1916.972656
Epoch 10, Loss 141.807480
Epoch 15, Loss 19.223967
Epoch 20, Loss 10.739697
Epoch 25, Loss 10.133256
Epoch 30, Loss 10.070797
Epoch 35, Loss 10.045960
Epoch 40, Loss 10.023793
Epoch 45, Loss 10.001883
Epoch 50, Loss 9.980053
Epoch 55, Loss 9.958303
Epoch 60, Loss 9.936625
Epoch 65, Loss 9.915021
Epoch 70, Loss 9.893493
Epoch 75, Loss 9.872033
Epoch 80, Loss 9.850648
Epoch 85, Loss 9.829334
Epoch 90, Loss 9.808096
Epoch 95, Loss 9.786930
Epoch 100, Loss 9.765836
Epoch 105, Loss 9.744808
Epoch 110, Loss 9.723856
Epoch 115, Loss 9.702973
Epoch 120, Loss 9.682160
Epoch 125, Loss 9.661422
Epoch 130, Loss 9.640753
Epoch 135, Loss 9.620153
Epoch 140, Loss 9.599624
Epoch 145, Loss 9.579163
Epoch 150, Loss 9.558773
Epoch 155, Loss 9.538450
Epoch 160, Loss 9.518197
Epoch 165, Loss 9.498015
Epoch 170, Loss 9.477897
Epoch 175, Loss 9.457853
Epoch 180, Loss 9.437873
Epoch 185, Loss 9.417962
Epoch 190, Loss 9.398118
Epoch 195, Loss 9.378341
Epoch 200, Loss 9.358633
Epoch 20

Epoch 1985, Loss 5.288480
Epoch 1990, Loss 5.282630
Epoch 1995, Loss 5.276799
Epoch 2000, Loss 5.270990
Epoch 2005, Loss 5.265198
Epoch 2010, Loss 5.259427
Epoch 2015, Loss 5.253676
Epoch 2020, Loss 5.247943
Epoch 2025, Loss 5.242229
Epoch 2030, Loss 5.236536
Epoch 2035, Loss 5.230863
Epoch 2040, Loss 5.225207
Epoch 2045, Loss 5.219571
Epoch 2050, Loss 5.213954
Epoch 2055, Loss 5.208355
Epoch 2060, Loss 5.202775
Epoch 2065, Loss 5.197216
Epoch 2070, Loss 5.191674
Epoch 2075, Loss 5.186150
Epoch 2080, Loss 5.180646
Epoch 2085, Loss 5.175162
Epoch 2090, Loss 5.169693
Epoch 2095, Loss 5.164244
Epoch 2100, Loss 5.158814
Epoch 2105, Loss 5.153404
Epoch 2110, Loss 5.148008
Epoch 2115, Loss 5.142632
Epoch 2120, Loss 5.137276
Epoch 2125, Loss 5.131938
Epoch 2130, Loss 5.126616
Epoch 2135, Loss 5.121312
Epoch 2140, Loss 5.116025
Epoch 2145, Loss 5.110758
Epoch 2150, Loss 5.105508
Epoch 2155, Loss 5.100277
Epoch 2160, Loss 5.095062
Epoch 2165, Loss 5.089865
Epoch 2170, Loss 5.084686
Epoch 2175, 

Epoch 3890, Loss 4.031446
Epoch 3895, Loss 4.029821
Epoch 3900, Loss 4.028200
Epoch 3905, Loss 4.026585
Epoch 3910, Loss 4.024973
Epoch 3915, Loss 4.023369
Epoch 3920, Loss 4.021769
Epoch 3925, Loss 4.020175
Epoch 3930, Loss 4.018587
Epoch 3935, Loss 4.017003
Epoch 3940, Loss 4.015423
Epoch 3945, Loss 4.013849
Epoch 3950, Loss 4.012281
Epoch 3955, Loss 4.010719
Epoch 3960, Loss 4.009161
Epoch 3965, Loss 4.007608
Epoch 3970, Loss 4.006062
Epoch 3975, Loss 4.004519
Epoch 3980, Loss 4.002981
Epoch 3985, Loss 4.001450
Epoch 3990, Loss 3.999922
Epoch 3995, Loss 3.998401
Epoch 4000, Loss 3.996884
Epoch 4005, Loss 3.995372
Epoch 4010, Loss 3.993865
Epoch 4015, Loss 3.992364
Epoch 4020, Loss 3.990865
Epoch 4025, Loss 3.989374
Epoch 4030, Loss 3.987888
Epoch 4035, Loss 3.986405
Epoch 4040, Loss 3.984928
Epoch 4045, Loss 3.983455
Epoch 4050, Loss 3.981989
Epoch 4055, Loss 3.980525
Epoch 4060, Loss 3.979067
Epoch 4065, Loss 3.977614
Epoch 4070, Loss 3.976167
Epoch 4075, Loss 3.974723
Epoch 4080, 

tensor([ 0.5730, -1.0005, -0.8148], requires_grad=True)

In [36]:
params = torch.tensor([4.0, 1.0, 0.0], requires_grad=True)
learning_rate = 1e-4
optimizer = optim.SGD([params], lr=learning_rate) # <1>

training_loop(
    n_epochs = 5000, 
    optimizer = optimizer,
    params = params, # <1> 
    t_u = t_un,
    t_c = t_c)

Epoch 5, Loss 1916.972656
Epoch 10, Loss 141.807480
Epoch 15, Loss 19.223967
Epoch 20, Loss 10.739697
Epoch 25, Loss 10.133256
Epoch 30, Loss 10.070797
Epoch 35, Loss 10.045960
Epoch 40, Loss 10.023793
Epoch 45, Loss 10.001883
Epoch 50, Loss 9.980053
Epoch 55, Loss 9.958303
Epoch 60, Loss 9.936625
Epoch 65, Loss 9.915021
Epoch 70, Loss 9.893493
Epoch 75, Loss 9.872033
Epoch 80, Loss 9.850648
Epoch 85, Loss 9.829334
Epoch 90, Loss 9.808096
Epoch 95, Loss 9.786930
Epoch 100, Loss 9.765836
Epoch 105, Loss 9.744808
Epoch 110, Loss 9.723856
Epoch 115, Loss 9.702973
Epoch 120, Loss 9.682160
Epoch 125, Loss 9.661422
Epoch 130, Loss 9.640753
Epoch 135, Loss 9.620153
Epoch 140, Loss 9.599624
Epoch 145, Loss 9.579163
Epoch 150, Loss 9.558773
Epoch 155, Loss 9.538450
Epoch 160, Loss 9.518197
Epoch 165, Loss 9.498015
Epoch 170, Loss 9.477897
Epoch 175, Loss 9.457853
Epoch 180, Loss 9.437873
Epoch 185, Loss 9.417962
Epoch 190, Loss 9.398118
Epoch 195, Loss 9.378341
Epoch 200, Loss 9.358633
Epoch 20

Epoch 1985, Loss 5.288480
Epoch 1990, Loss 5.282630
Epoch 1995, Loss 5.276799
Epoch 2000, Loss 5.270990
Epoch 2005, Loss 5.265198
Epoch 2010, Loss 5.259427
Epoch 2015, Loss 5.253676
Epoch 2020, Loss 5.247943
Epoch 2025, Loss 5.242229
Epoch 2030, Loss 5.236536
Epoch 2035, Loss 5.230863
Epoch 2040, Loss 5.225207
Epoch 2045, Loss 5.219571
Epoch 2050, Loss 5.213954
Epoch 2055, Loss 5.208355
Epoch 2060, Loss 5.202775
Epoch 2065, Loss 5.197216
Epoch 2070, Loss 5.191674
Epoch 2075, Loss 5.186150
Epoch 2080, Loss 5.180646
Epoch 2085, Loss 5.175162
Epoch 2090, Loss 5.169693
Epoch 2095, Loss 5.164244
Epoch 2100, Loss 5.158814
Epoch 2105, Loss 5.153404
Epoch 2110, Loss 5.148008
Epoch 2115, Loss 5.142632
Epoch 2120, Loss 5.137276
Epoch 2125, Loss 5.131938
Epoch 2130, Loss 5.126616
Epoch 2135, Loss 5.121312
Epoch 2140, Loss 5.116025
Epoch 2145, Loss 5.110758
Epoch 2150, Loss 5.105508
Epoch 2155, Loss 5.100277
Epoch 2160, Loss 5.095062
Epoch 2165, Loss 5.089865
Epoch 2170, Loss 5.084686
Epoch 2175, 

Epoch 3890, Loss 4.031446
Epoch 3895, Loss 4.029821
Epoch 3900, Loss 4.028200
Epoch 3905, Loss 4.026585
Epoch 3910, Loss 4.024973
Epoch 3915, Loss 4.023369
Epoch 3920, Loss 4.021769
Epoch 3925, Loss 4.020175
Epoch 3930, Loss 4.018587
Epoch 3935, Loss 4.017003
Epoch 3940, Loss 4.015423
Epoch 3945, Loss 4.013849
Epoch 3950, Loss 4.012281
Epoch 3955, Loss 4.010719
Epoch 3960, Loss 4.009161
Epoch 3965, Loss 4.007608
Epoch 3970, Loss 4.006062
Epoch 3975, Loss 4.004519
Epoch 3980, Loss 4.002981
Epoch 3985, Loss 4.001450
Epoch 3990, Loss 3.999922
Epoch 3995, Loss 3.998401
Epoch 4000, Loss 3.996884
Epoch 4005, Loss 3.995372
Epoch 4010, Loss 3.993865
Epoch 4015, Loss 3.992364
Epoch 4020, Loss 3.990865
Epoch 4025, Loss 3.989374
Epoch 4030, Loss 3.987888
Epoch 4035, Loss 3.986405
Epoch 4040, Loss 3.984928
Epoch 4045, Loss 3.983455
Epoch 4050, Loss 3.981989
Epoch 4055, Loss 3.980525
Epoch 4060, Loss 3.979067
Epoch 4065, Loss 3.977614
Epoch 4070, Loss 3.976167
Epoch 4075, Loss 3.974723
Epoch 4080, 

tensor([ 0.5730, -1.0005, -0.8148], requires_grad=True)

In [36]:
params = torch.tensor([4.0, 1.0, 0.0], requires_grad=True)
learning_rate = 1e-4
optimizer = optim.SGD([params], lr=learning_rate) # <1>

training_loop(
    n_epochs = 5000, 
    optimizer = optimizer,
    params = params, # <1> 
    t_u = t_un,
    t_c = t_c)

Epoch 5, Loss 1916.972656
Epoch 10, Loss 141.807480
Epoch 15, Loss 19.223967
Epoch 20, Loss 10.739697
Epoch 25, Loss 10.133256
Epoch 30, Loss 10.070797
Epoch 35, Loss 10.045960
Epoch 40, Loss 10.023793
Epoch 45, Loss 10.001883
Epoch 50, Loss 9.980053
Epoch 55, Loss 9.958303
Epoch 60, Loss 9.936625
Epoch 65, Loss 9.915021
Epoch 70, Loss 9.893493
Epoch 75, Loss 9.872033
Epoch 80, Loss 9.850648
Epoch 85, Loss 9.829334
Epoch 90, Loss 9.808096
Epoch 95, Loss 9.786930
Epoch 100, Loss 9.765836
Epoch 105, Loss 9.744808
Epoch 110, Loss 9.723856
Epoch 115, Loss 9.702973
Epoch 120, Loss 9.682160
Epoch 125, Loss 9.661422
Epoch 130, Loss 9.640753
Epoch 135, Loss 9.620153
Epoch 140, Loss 9.599624
Epoch 145, Loss 9.579163
Epoch 150, Loss 9.558773
Epoch 155, Loss 9.538450
Epoch 160, Loss 9.518197
Epoch 165, Loss 9.498015
Epoch 170, Loss 9.477897
Epoch 175, Loss 9.457853
Epoch 180, Loss 9.437873
Epoch 185, Loss 9.417962
Epoch 190, Loss 9.398118
Epoch 195, Loss 9.378341
Epoch 200, Loss 9.358633
Epoch 20

Epoch 1985, Loss 5.288480
Epoch 1990, Loss 5.282630
Epoch 1995, Loss 5.276799
Epoch 2000, Loss 5.270990
Epoch 2005, Loss 5.265198
Epoch 2010, Loss 5.259427
Epoch 2015, Loss 5.253676
Epoch 2020, Loss 5.247943
Epoch 2025, Loss 5.242229
Epoch 2030, Loss 5.236536
Epoch 2035, Loss 5.230863
Epoch 2040, Loss 5.225207
Epoch 2045, Loss 5.219571
Epoch 2050, Loss 5.213954
Epoch 2055, Loss 5.208355
Epoch 2060, Loss 5.202775
Epoch 2065, Loss 5.197216
Epoch 2070, Loss 5.191674
Epoch 2075, Loss 5.186150
Epoch 2080, Loss 5.180646
Epoch 2085, Loss 5.175162
Epoch 2090, Loss 5.169693
Epoch 2095, Loss 5.164244
Epoch 2100, Loss 5.158814
Epoch 2105, Loss 5.153404
Epoch 2110, Loss 5.148008
Epoch 2115, Loss 5.142632
Epoch 2120, Loss 5.137276
Epoch 2125, Loss 5.131938
Epoch 2130, Loss 5.126616
Epoch 2135, Loss 5.121312
Epoch 2140, Loss 5.116025
Epoch 2145, Loss 5.110758
Epoch 2150, Loss 5.105508
Epoch 2155, Loss 5.100277
Epoch 2160, Loss 5.095062
Epoch 2165, Loss 5.089865
Epoch 2170, Loss 5.084686
Epoch 2175, 

Epoch 3890, Loss 4.031446
Epoch 3895, Loss 4.029821
Epoch 3900, Loss 4.028200
Epoch 3905, Loss 4.026585
Epoch 3910, Loss 4.024973
Epoch 3915, Loss 4.023369
Epoch 3920, Loss 4.021769
Epoch 3925, Loss 4.020175
Epoch 3930, Loss 4.018587
Epoch 3935, Loss 4.017003
Epoch 3940, Loss 4.015423
Epoch 3945, Loss 4.013849
Epoch 3950, Loss 4.012281
Epoch 3955, Loss 4.010719
Epoch 3960, Loss 4.009161
Epoch 3965, Loss 4.007608
Epoch 3970, Loss 4.006062
Epoch 3975, Loss 4.004519
Epoch 3980, Loss 4.002981
Epoch 3985, Loss 4.001450
Epoch 3990, Loss 3.999922
Epoch 3995, Loss 3.998401
Epoch 4000, Loss 3.996884
Epoch 4005, Loss 3.995372
Epoch 4010, Loss 3.993865
Epoch 4015, Loss 3.992364
Epoch 4020, Loss 3.990865
Epoch 4025, Loss 3.989374
Epoch 4030, Loss 3.987888
Epoch 4035, Loss 3.986405
Epoch 4040, Loss 3.984928
Epoch 4045, Loss 3.983455
Epoch 4050, Loss 3.981989
Epoch 4055, Loss 3.980525
Epoch 4060, Loss 3.979067
Epoch 4065, Loss 3.977614
Epoch 4070, Loss 3.976167
Epoch 4075, Loss 3.974723
Epoch 4080, 

tensor([ 0.5730, -1.0005, -0.8148], requires_grad=True)

In [5]:
def loss_fn(t_p, t_c):
    squared_diffs = (t_p - t_c)**2
    return squared_diffs.mean()

In [6]:
import torch.optim as optim

dir(optim)

['ASGD',
 'Adadelta',
 'Adagrad',
 'Adam',
 'AdamW',
 'Adamax',
 'LBFGS',
 'NAdam',
 'Optimizer',
 'RAdam',
 'RMSprop',
 'Rprop',
 'SGD',
 'SparseAdam',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_functional',
 '_multi_tensor',
 'lr_scheduler',
 'swa_utils']

In [21]:
params = torch.tensor([1.0, 1.0, 0.0], requires_grad=True)
learning_rate = 1e-5
optimizer = optim.SGD([params], lr=learning_rate)

In [23]:
params = torch.tensor([1.0, 1.0, 0.0], requires_grad=True)
learning_rate = 1e-2
optimizer = optim.SGD([params], lr=learning_rate)

t_p = model(t_un, *params)
loss = loss_fn(t_p, t_c)

optimizer.zero_grad() # <1>
loss.backward()
optimizer.step()

params

tensor([-16.3953,  -1.7968,  -0.4818], requires_grad=True)

In [26]:
def training_loop(n_epochs, optimizer, params, t_u, t_c):
    for epoch in range(1, n_epochs + 1):
        t_p = model(t_u, *params) 
        loss = loss_fn(t_p, t_c)
        
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        if epoch % 5 == 0:
            print('Epoch %d, Loss %f' % (epoch, float(loss)))
            
    return params

In [36]:
params = torch.tensor([4.0, 1.0, 0.0], requires_grad=True)
learning_rate = 1e-4
optimizer = optim.SGD([params], lr=learning_rate) # <1>

training_loop(
    n_epochs = 5000, 
    optimizer = optimizer,
    params = params, # <1> 
    t_u = t_un,
    t_c = t_c)

Epoch 5, Loss 1916.972656
Epoch 10, Loss 141.807480
Epoch 15, Loss 19.223967
Epoch 20, Loss 10.739697
Epoch 25, Loss 10.133256
Epoch 30, Loss 10.070797
Epoch 35, Loss 10.045960
Epoch 40, Loss 10.023793
Epoch 45, Loss 10.001883
Epoch 50, Loss 9.980053
Epoch 55, Loss 9.958303
Epoch 60, Loss 9.936625
Epoch 65, Loss 9.915021
Epoch 70, Loss 9.893493
Epoch 75, Loss 9.872033
Epoch 80, Loss 9.850648
Epoch 85, Loss 9.829334
Epoch 90, Loss 9.808096
Epoch 95, Loss 9.786930
Epoch 100, Loss 9.765836
Epoch 105, Loss 9.744808
Epoch 110, Loss 9.723856
Epoch 115, Loss 9.702973
Epoch 120, Loss 9.682160
Epoch 125, Loss 9.661422
Epoch 130, Loss 9.640753
Epoch 135, Loss 9.620153
Epoch 140, Loss 9.599624
Epoch 145, Loss 9.579163
Epoch 150, Loss 9.558773
Epoch 155, Loss 9.538450
Epoch 160, Loss 9.518197
Epoch 165, Loss 9.498015
Epoch 170, Loss 9.477897
Epoch 175, Loss 9.457853
Epoch 180, Loss 9.437873
Epoch 185, Loss 9.417962
Epoch 190, Loss 9.398118
Epoch 195, Loss 9.378341
Epoch 200, Loss 9.358633
Epoch 20

Epoch 1985, Loss 5.288480
Epoch 1990, Loss 5.282630
Epoch 1995, Loss 5.276799
Epoch 2000, Loss 5.270990
Epoch 2005, Loss 5.265198
Epoch 2010, Loss 5.259427
Epoch 2015, Loss 5.253676
Epoch 2020, Loss 5.247943
Epoch 2025, Loss 5.242229
Epoch 2030, Loss 5.236536
Epoch 2035, Loss 5.230863
Epoch 2040, Loss 5.225207
Epoch 2045, Loss 5.219571
Epoch 2050, Loss 5.213954
Epoch 2055, Loss 5.208355
Epoch 2060, Loss 5.202775
Epoch 2065, Loss 5.197216
Epoch 2070, Loss 5.191674
Epoch 2075, Loss 5.186150
Epoch 2080, Loss 5.180646
Epoch 2085, Loss 5.175162
Epoch 2090, Loss 5.169693
Epoch 2095, Loss 5.164244
Epoch 2100, Loss 5.158814
Epoch 2105, Loss 5.153404
Epoch 2110, Loss 5.148008
Epoch 2115, Loss 5.142632
Epoch 2120, Loss 5.137276
Epoch 2125, Loss 5.131938
Epoch 2130, Loss 5.126616
Epoch 2135, Loss 5.121312
Epoch 2140, Loss 5.116025
Epoch 2145, Loss 5.110758
Epoch 2150, Loss 5.105508
Epoch 2155, Loss 5.100277
Epoch 2160, Loss 5.095062
Epoch 2165, Loss 5.089865
Epoch 2170, Loss 5.084686
Epoch 2175, 

Epoch 3890, Loss 4.031446
Epoch 3895, Loss 4.029821
Epoch 3900, Loss 4.028200
Epoch 3905, Loss 4.026585
Epoch 3910, Loss 4.024973
Epoch 3915, Loss 4.023369
Epoch 3920, Loss 4.021769
Epoch 3925, Loss 4.020175
Epoch 3930, Loss 4.018587
Epoch 3935, Loss 4.017003
Epoch 3940, Loss 4.015423
Epoch 3945, Loss 4.013849
Epoch 3950, Loss 4.012281
Epoch 3955, Loss 4.010719
Epoch 3960, Loss 4.009161
Epoch 3965, Loss 4.007608
Epoch 3970, Loss 4.006062
Epoch 3975, Loss 4.004519
Epoch 3980, Loss 4.002981
Epoch 3985, Loss 4.001450
Epoch 3990, Loss 3.999922
Epoch 3995, Loss 3.998401
Epoch 4000, Loss 3.996884
Epoch 4005, Loss 3.995372
Epoch 4010, Loss 3.993865
Epoch 4015, Loss 3.992364
Epoch 4020, Loss 3.990865
Epoch 4025, Loss 3.989374
Epoch 4030, Loss 3.987888
Epoch 4035, Loss 3.986405
Epoch 4040, Loss 3.984928
Epoch 4045, Loss 3.983455
Epoch 4050, Loss 3.981989
Epoch 4055, Loss 3.980525
Epoch 4060, Loss 3.979067
Epoch 4065, Loss 3.977614
Epoch 4070, Loss 3.976167
Epoch 4075, Loss 3.974723
Epoch 4080, 

tensor([ 0.5730, -1.0005, -0.8148], requires_grad=True)